### ISSUE TITLE
Request for the license of this repo

### ISSUE THREAD

**Issue by sparkcontext** [newbienewbie/InDirectLine#6]
suggested by **What can I assume if a publicly published project has no license?**
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

May i request for a license of this repo please?

**Comment by newbienewbie** [comment]
@sparkcontext Thanks for contacting me. I added the MIT license info this morning. :) 

See [commit#f354110ce87b1a003226611dde5f9d3743bf8331](https://github.com/newbienewbie/InDirectLine/commit/f354110ce87b1a003226611dde5f9d3743bf8331)

**Comment by sparkcontext** [comment]
Dear ITminus,

Thank you very much!
To show my appreciation, may I ask if I can buy you a coffee or something?

Regards,
sparkcontext

**Comment by newbienewbie** [comment]
@sparkcontext  You're such a kind person.  I'm so glad that my code helps .  Several years ago when I was a super newbie, I learned how to program every night. That were really hard days.  I have never thought one day I could I get donation because of my code.  Unfortunately, for some particular reason, I have no approaches to accept money from out of my country. The GitHub sponsor is not avaiable for China.  Anyway, thanks for your feedback. It would encourage me to write more code in future.
